namespace: ansible
name: hetzner
version: 1.0.0
readme: README.md
authors: null
description: null
license: null
license_file: null
tags: null
dependencies:
  ansible.netcommon: '>=1.0'
  ansible.unix: '>=1.0'
  ansible.infoblox: '>=1.0'
repository: git@github.com:ansible-collection-migration/ansible.hetzner.git
documentation: https://github.com/ansible-collection-migration/ansible.hetzner/tree/master/docs
homepage: https://github.com/ansible-collection-migration/ansible.hetzner
issues: https://github.com/ansible-collection-migration/ansible.hetzner/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
